media:
  input: assets
  output: assets

content:
  - name: pagina
    label: Muy Nuestro
    type: file
    path: index.html
    fields:
      - name: body
        label: Contenido de la página
        type: code
        options:
          language: html
